name: Run Ci
run-name: ${{ github.actor}}
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - 'main'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: "Install dependencies"
        run: "npm ci"
      -
        name: "Run tests"
        run: "npm run cy:ci"

